# https://github.com/vorburger/dotfiles/blob/master/dotfiles/gpg-agent.conf
# https://github.com/drduh/config/blob/master/gpg-agent.conf

enable-ssh-support

# Cache PINs for 8 hours (28800 seconds)
default-cache-ttl 28800
default-cache-ttl-ssh 28800
max-cache-ttl 28800
max-cache-ttl-ssh 28800

# Require pinentry only once per smartcard session
allow-preset-passphrase

#pinentry-program /usr/bin/pinentry-curses
#pinentry-program /usr/local/bin/pinentry-curses
#pinentry-program /usr/bin/pinentry-gnome3
